project:
  type: website
  output-dir: docs

website:
  title: "![](/images/outlier-favicon.png){height=2em}"
  repo-url: https://github.com/juliansiebertdata/website
  repo-actions: issue
  repo-subdir: "docs"
  page-navigation: true
  back-to-top-navigation: true
  favicon: "images/outlier-favicon.png"
  open-graph: true
  search:
      location: navbar
      type: textbox
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - sidebar:research
      - text: "CV"
        href: "mydocuments/cv-juliansiebert.pdf"
  sidebar:
    - id: research
      title: "Agricultural Research"
      style: "floating"
      contents:
        - href: about.qmd
          text: "Your first day."
  page-footer: 
    left: "Agricultural Research is a web-project by Julian Siebert." 
    right: 
      - text: "Give Feedback and Critic"
      - icon: envelope-at
        href: mailto:ju.siebert@live.de?&subject=Feedback for your book&body=Add what you want to suggest
      - text: "| Github"
      - icon: github
        href: https://github.com/juliansiebertdata/
  reader-mode: false

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: "Ubuntu"
    toc: true
    toc-title: "On this page"
    toc-expand: true
    embed-resources: true
    link-external-newwindow: true
    include-in-header: "web-elements/progressbar.html"
    #citation-location: margin

resources: 
  - "/images*"
  - "/web-elements*"
  - "/icons*"

crossref:
  custom:
    - kind: float
      reference-prefix: Video
      key: vid


